### ISSUE TITLE
Average attenuation template: scaling factor as a fitable parameter? 

### ISSUE THREAD

**Issue by dcorre** [karllark/dust_attenuation#13]
For average attenuation curves, should we declare the scaling factor (Av or tau) as a fitable parameter in the class (for instance in the C00) or should we return the normalised attenuation curve and then find a way to fit the scaling factor.

My personal view is that we should make a distinction between the shape of the attenuation curve, i.e normalised attenuation curve, and the amount of attenuation, i.e scaling factor.

**Comment by karllark** [comment]
Giving this more thought, I think A(V) should be a fittable parameter.
The reason is the for the most correct attenuation models - the ones based on radiative transfer results - A(V) has to be a parameter as the shape is dependent on A(V).  While this is not true for the average models like Calzetti00, I think it would be best to have as similar interface as possible between the models.

**Comment by dcorre** [comment]
I agree, and that's good as this is already what C00 and WG00 are doing.

**Comment by karllark** [comment]
Great.  We'll stay with what we are doing.  :-)
